const _techStacks = [
  "Amazon Alexa",
  "ChatGPT",
  "Dependabot",
  "Google Assistant",
  "Hyperledger",
  "Blogger",
  "Dev",
  "Ghost",
  "Hashnode",
  "Medium",
  "Micro.blog",
  "Rss",
  "Substack",
  "Wix",
  "Brave",
  "Edge",
  "Firefox",
  "Google Chrome",
  "IE",
  "Opera",
  "Safari",
  "Tor",
  "Vivaldi",
  "CircleCI",
  "ChipperCI",
  "CloudBees",
  "GitLab CI",
  "GitHub Actions",
  "TeamCity",
  "Travis CI",
  "Octopus Deploy",
  "Dropbox",
  "Google Drive",
  "Mega.nz",
  "Microsoft OneDrive",
  "Next Cloud",
  "OneDrive",
  "Proton Drive",
  "Amp",
  "Bitcoin",
  "Bitcoin Cash",
  "Bitcoin SV",
  "Binance",
  "Chainlink",
  "Dogecoin",
  "Dash",
  "Ethereum",
  "Iota",
  "Litecoin",
  "Monero",
  "Polkadot",
  "Stellar",
  "Tether",
  "Xrp",
  "Z Cash",
  "Amazon DynamoDB",
  "Cassandra",
  "Cockroach Labs",
  "Couchbase",
  "Firebase",
  "InfluxDB",
  "MariaDB",
  "MusicBrainz",
  "Microsoft SQL Server",
  "MongoDB",
  "MySQL",
  "Neo4J",
  "PlanetScale",
  "Postgres",
  "Realm",
  "Redis",
  "Single Store",
  "SQLite",
  "Supabase",
  "SurrealDB",
  "Teradata",
  "Adobe",
  "Adobe Acrobat Reader",
  "Adobe After Effects",
  "Adobe Audition",
  "Adobe Creative Cloud",
  "Adobe Dreamweaver",
  "Adobe Fonts",
  "Adobe Illustrator",
  "Adobe InDesign",
  "Adobe Lightroom",
  "Adobe Lightroom Classic",
  "Adobe Photoshop",
  "Adobe Premiere Pro",
  "Adobe XD",
  "Aseprite",
  "Affinity Designer",
  "Affinity Photo",
  "Blender",
  "Canva",
  "Dribbble",
  "Figma",
  "Framer",
  "Gimp",
  "Inkscape",
  "Invision",
  "Krita",
  "Proto.io",
  "Sketch",
  "Storybook",
  "CodeChef",
  "Codeforces",
  "CodePen",
  "Hackerearth",
  "Hackerrank",
  "LeetCode",
  "Kaggle",
  "OnePlus Forums",
  "Quora",
  "Reddit",
  "ResearchGate",
  "Stack Exchange",
  "Stack Overflow",
  "XDA-Developers",
  "Bookstack",
  "Wikipedia",
  "Wiki.js",
  "Codecademy",
  "Codingninjas",
  "Codewars",
  "Coursera",
  "Datacamp",
  "Duolingo",
  "edX",
  "Exercism",
  "FreeCodeCamp",
  "Future Learn",
  "GeeksforGeeks",
  "Khan Academy",
  "MDN Web Docs",
  "Microsoft Learn",
  "Pluralsight",
  "Scrimba",
  "Skill Share",
  "Udacity",
  "Udemy",
  "Amazon Pay",
  "Apple Pay",
  "Buy Me a Coffee",
  "Github Sponsors",
  "Google Pay",
  "Ko-Fi",
  "LiberaPay",
  "Patreon",
  "PayPal",
  "Paytm",
  "Phonepe",
  "Samsung Pay",
  "Wise",
  ".NET",
  "AdonisJS",
  "Anaconda",
  "Angular",
  "Angular.js",
  "Ant Design",
  "Apache Spark",
  "Apache Kafka",
  "Apache Hadoop",
  "Apache Hive",
  "Apollo GraphQL",
  "Aurelia",
  "Blazor",
  "Bootstrap",
  "Buefy",
  "Bulma",
  "Bun",
  "Chakra UI",
  "Chart.js",
  "Code Igniter",
  "DaisyUI",
  "Deno JS",
  "Directus",
  "Django",
  "DjangoREST",
  "Drupal",
  "Electron.js",
  "Ember",
  "Expo",
  "Express.js",
  "FastAPI",
  "Fastify",
  "Flask",
  "Flutter",
  "Gatsby.js",
  "Green Sock",
  "Gulp",
  "Insomnia",
  "Hugo",
  "Ionic",
  "Jasmine",
  "Jinja",
  "Joomla",
  "jQuery",
  "JWT/JSON Web Token",
  "Laravel",
  "Less",
  "MUI",
  "Meteor JS",
  "MaxCompute",
  "NPM",
  "NestJS",
  "Next JS",
  "Node.js",
  "Nodemon",
  "Node-RED",
  "Nuxt JS",
  "Nx",
  "OpenCV",
  "OpenGL",
  "P5js",
  "PNPM",
  "Prefect",
  "Pug",
  "Qt",
  "Quasar",
  "ROS",
  "RabbitMQ",
  "Rails",
  "React",
  "React Native",
  "React Query",
  "React Router",
  "React Hook Form",
  "Redux",
  "Remix",
  "RollupJS",
  "RxDB",
  "RxJS",
  "SASS",
  "Semantic UI React",
  "Socket.io",
  "SolidJS",
  "Spring",
  "Strapi",
  "Styled Components",
  "Stylus",
  "Svelte",
  "Symfony",
  "TailwindCSS",
  "Tauri",
  "Three.js",
  "Thymeleaf",
  "TypeGraphQL",
  "UnoCSS",
  "Vite",
  "Vue.js",
  "Vuetify",
  "WebGL",
  "Webpack",
  "Web3.js",
  "WindiCSS",
  "WordPress",
  "Xamarin",
  "Yarn",
  "Analogue",
  "Battle.net",
  "EA",
  "Epic Games",
  "Godot Engine",
  "Humble Bundle",
  "Itch.io",
  "nVIDIA",
  "PlayStation Network",
  "Riot Games",
  "Square Enix",
  "Steam",
  "Ubisoft",
  "Unity",
  "Unreal Engine",
  "Xbox",
  "3DS",
  "Gamecube",
  "Playstation",
  "Playstation 2",
  "Playstation 3",
  "Playstation 4",
  "Playstation 5",
  "Playstation Vita",
  "Switch",
  "Wii",
  "Wii U",
  "Xbox",
  "Alibaba Cloud",
  "AWS",
  "Azure",
  "Cloudflare",
  "Codeberg",
  "Datadog",
  "DigitalOcean",
  "Firebase",
  "Github Pages",
  "Glitch",
  "Google Cloud",
  "Heroku",
  "Linode",
  "Netlify",
  "Oracle",
  "OpenStack",
  "OVH",
  "Render",
  "Scaleway",
  "Vercel",
  "Vultr",
  "Android Studio",
  "Atom",
  "CLion",
  "CodePen",
  "CodeSandbox",
  "Eclipse",
  "Emacs",
  "GoLand",
  "IntelliJ IDEA",
  "Jupyter Notebook",
  "Neovim",
  "NetBeans IDE",
  "Notepad++",
  "Obsidian",
  "P5js Editor",
  "PhpStorm",
  "PyCharm",
  "Replit",
  "Rider",
  "RStudio",
  "Spyder",
  "Sublime Text",
  "Vim",
  "Visual Studio Code",
  "VS Code Insiders",
  "Visual Studio",
  "WebStorm",
  "Xcode",
  "Zend",
  "Stackblitz",
  "Apache Groovy",
  "C",
  "C#",
  "C++",
  "Clojure",
  "Crystal",
  "CSS3",
  "Dart",
  "Elixir",
  "Elm",
  "Erlang",
  "Fortran",
  "Go/Golang",
  "GraphQL",
  "Haskell",
  "HTML5",
  "Java",
  "JavaScript",
  "Julia",
  "Kotlin",
  "LaTeX",
  "Lua",
  "Markdown",
  "Nim",
  "Nix",
  "Objective-C",
  "Octave",
  "Org Mode",
  "Perl",
  "PHP",
  "PowerShell",
  "Python",
  "R",
  "ReScript",
  "Ruby",
  "Rust",
  "Scala",
  "Shell Script",
  "Solidity",
  "Swift",
  "TypeScript",
  "Windows Terminal",
  "Zig",
  "Keras",
  "Matplotlib",
  "mlflow",
  "NumPy",
  "Pandas",
  "Plotly",
  "PyTorch",
  "scikit-learn",
  "SciPy",
  "TensorFlow",
  "Apple Music",
  "Audacity",
  "Deezer",
  "Sound Cloud",
  "Spotify",
  "Shazam",
  "Tidal",
  "YouTube Music",
  "LibreOffice",
  "Microsoft",
  "Microsoft Access",
  "Microsoft Excel",
  "Microsoft Office",
  "Microsoft PowerPoint",
  "Microsoft SharePoint",
  "Microsoft Visio",
  "Microsoft Word",
  "Alpine Linux",
  "Android",
  "Arch",
  "Cent OS",
  "Chrome OS",
  "Debian",
  "Deepin",
  "Elementary OS",
  "Fedora",
  "FreeBSD",
  "Gentoo",
  "iOS",
  "Kali",
  "Kubuntu",
  "Linux",
  "Linux Mint",
  "Lubuntu",
  "Lineageos",
  "Manjaro",
  "MX Linux",
  "macOS",
  "NixOS",
  "OpenWRT",
  "OpenBSD",
  "openSUSE",
  "Pop!_OS",
  "Red Hat",
  "Rocky Linux",
  "Solus",
  "SUSE",
  "Slackware",
  "Tails",
  "Ubuntu",
  "Unraid",
  "Wear OS",
  "Windows",
  "Windows 11",
  "Windows 95",
  "Windows XP",
  "Zorin OS",
  "Hibernate",
  "Prisma",
  "Sequelize",
  "Quill",
  "Airbnb",
  "Alfred",
  "Ansible",
  "Aqua Sec",
  "Arduino",
  "Babel",
  "Bitwarden",
  "Cisco",
  "CMake",
  "CodeCov",
  "Confluence",
  "Docker",
  "ESLint",
  "ElasticSearch",
  "Espressif",
  "Gradle",
  "Grafana",
  "Home Assistant",
  "Homebridge",
  "Jellyfin",
  "Jira",
  "Kubernetes",
  "Mosquitto",
  "Notion",
  "OpenSea",
  "Packer",
  "Pi-Hole",
  "Plex",
  "Portfolio",
  "Postman",
  "Power BI",
  "Prezi",
  "Prometheus",
  "Rancher",
  "Raspberry Pi",
  "SonarLint",
  "SonarQube",
  "Splunk",
  "Swagger",
  "TOR",
  "Terraform",
  "Trello",
  "Uber",
  "Ubiquiti",
  "Vagrant",
  "Wireguard",
  "XFCE",
  "Zigbee",
  "Qiskit",
  "Baidu",
  "Bing",
  "DuckDuckGo",
  "Google",
  "Yahoo!",
  "Apache",
  "Apache Airflow",
  "Apache Ant",
  "Apache Flink",
  "Apache Maven",
  "Apache Tomcat",
  "Gunicorn",
  "Jenkins",
  "Nginx",
  "Airtable",
  "Discord",
  "Facebook",
  "Gmail",
  "Goodreads",
  "Google Meet",
  "Instagram",
  "KakaoTalk",
  "Line",
  "LinkedIn",
  "Linktree",
  "Meetup",
  "Messenger",
  "Mastodon",
  "Outlook",
  "Odysee",
  "Pinterest",
  "Protonmail",
  "Polywork",
  "Reddit",
  "Signal",
  "Skype",
  "Slack",
  "Snapchat",
  "TeamSpeak",
  "Telegram",
  "Tencent QQ",
  "TikTok",
  "Tumblr",
  "Tutanota",
  "Twitch",
  "Twitter",
  "Viber",
  "WeChat",
  "WhatsApp",
  "Wire",
  "Xbox",
  "XING",
  "YouTube",
  "Zoom",
  "Threads",
  "Apple",
  "ASUS",
  "BlackBerry",
  "Huawei",
  "Lenovo",
  "LG",
  "OnePlus",
  "Motorola",
  "Nokia",
  "Samsung",
  "Xiaomi",
  "App Store",
  "F-Droid",
  "Play Store",
  "Amazon Prime",
  "Apple TV",
  "Crunchyroll",
  "Facebook Gaming",
  "Facebook Live",
  "Fire TV",
  "Hulu",
  "Netflix",
  "Roku",
  "Twitch",
  "Youtube Gaming",
  "Cypress",
  "Jasmine",
  "Jest",
  "Mocha",
  "Selenium",
  "Testing Library",
  "Apache Subversion",
  "Bitbucket",
  "Forgejo",
  "Git",
  "Gitea",
  "Gitee",
  "GitHub",
  "GitLab",
  "Gitpod",
  "Mercurial",
  "Perforce Helix",
  "Fitbit",
  "AngelList",
  "Behance",
  "Freelancer",
  "Hacker Earth",
  "HackerRank",
  "Indeed",
  "Upwork",
];

// 大文字、小文字を区別しないソート
// https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
function caseInsensitiveSort(a: string, b: string) {
  return a.toLowerCase().localeCompare(b.toLowerCase());
}

// 重複の排除とソート
export const techStacks = Array.from(new Set(_techStacks)).sort(
  caseInsensitiveSort
);
