import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeRegistry from "./ThemeRegistry";
import { Box } from "@mui/material";
import { RecoilRoot } from "recoil";
import { Header } from "./Header";
import { RecoilProvider } from "./RecoilProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Careers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeRegistry options={{ key: "mui" }}>
          <RecoilProvider>{children}</RecoilProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
