import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeRegistry from "./ThemeRegistry";
import { RecoilProvider } from "./RecoilProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Careers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="root">
          <ThemeRegistry options={{ key: "mui" }}>
            <RecoilProvider>{children}</RecoilProvider>
          </ThemeRegistry>
        </div>
      </body>
    </html>
  );
}
